---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  gateways:
  - {{ .Values.control_plane.namespace }}/default
  hosts:
  - {{ .Values.control_plane.ingressgateway.host }}
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080
  - match:
    - uri:
        exact: /nginx-echo-headers
    route:
    - destination:
        host: nginx-echo-headers
        port:
          number: 8080
...